### PR TITLE
From https://github.com/armenzg/firefox-code-coverage-frontend

### PR DESCRIPTION
**Pull request by klahnakoski**
Please, both of you, review this. Mostly, the *.css file, which is a mess

### CODE REVIEW

**Comment by LinkaiQi** [comment]
I will work on this :smirk:

**Comment by klahnakoski** [comment]
Thank you!

**Comment by LinkaiQi** [comment]
New to this version:
1. Our ```fileviewer``` has a new look!
Keep our  ```file-viewer``` consistent with Armen's ```diff-viewer``` styling.
2. Resolve merge conflicts from Armen's master branch.
3. Solve a issue that causes ```file_line``` onHover and onSelected styling cannot display properly.
4. Refine ```FileViewerMeta``` component, add http requests status section in the ```FileViewerMeta```.

screen-shot-1
screen-shot-2

Try: http://localhost:3000/file?revision=c616a6fd5e4b&path=/accessible/atk/Platform.cpp

**Comment by yuenj** [comment]
whoa looks nice!

**Comment by klahnakoski** [comment]
@yuenj if you are happy with this, please merge it.

**Comment by yuenj** [comment]
Did you run yarn lint?  Otherwise, looks good!

**Pull request merged**
